### ISSUE TITLE
Idea: Meta-Charts

### ISSUE THREAD

**Issue by jphastings** [toby/playgrub#23]
It might be quite fun to have a permanent XSPF available on playgrub of the most grubbed songs, a kind of meta-chart of the songs that crop up most often.

You'd have to be quite careful to prevent one site being scraped many times ruining weightings while also acknowledging its popularity - but who knows, maybe RATM will be vying for playgrub's coveted #1 spot next year…

**Comment by toby** [comment]
I agree this would be cool. I've played around a bit with artist level popularity lists and the results are very interesting. The Google App Engine datastore doesn't make it easy though. Afaik there's no way to do fuzzy matching (or even case insensitive matching!) so disambiguation is a challenge. As you say, we'd have to watch out for multiple submits as well (that's probably something that should be fixed in general too).

**Comment by jphastings** [comment]
Oh yeah, that is a bit of a pain, I guess you could do it in the python - incrementing/adding a track/artist pair occurence value everytime its grubbed. A cron job could reduce every value every few hours & remove < 0 tracks, leaving a constantly evolving chart. Can last.fm's data be used to deal with ambiguous metadata?
